/*
 * Buffer scoring AI, autogenerated scores
 *
 * Copyright (C) 2014 Lauri Kasanen   All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef MAGIC_H
#define MAGIC_H

#define input0w -0.207843
#define input0b 0.231373
#define input1w -0.176471
#define input1b 0.262745
#define input2w -0.027451
#define input2b 0.349020
#define input3w -0.607843
#define input3b 0.905882
#define input4w 0.866667
#define input4b -0.741176
#define input5w 0.929412
#define input5b 0.325490
#define input6w 0.654902
#define input6b 0.207843
#define input7w -0.615686
#define input7b -0.976471
#define input8w -0.764706
#define input8b -0.803922
#define hidden0w0 0.341177
#define hidden0w1 -0.929412
#define hidden0w2 0.427451
#define hidden0w3 -0.380392
#define hidden0w4 -0.427451
#define hidden0w5 -0.082353
#define hidden0w6 -0.215686
#define hidden0w7 0.756863
#define hidden0w8 -0.945098
#define hidden0b -0.764706
#define hidden1w0 -0.372549
#define hidden1w1 -0.294118
#define hidden1w2 -0.223529
#define hidden1w3 -0.341176
#define hidden1w4 0.490196
#define hidden1w5 -0.325490
#define hidden1w6 0.098039
#define hidden1w7 0.929412
#define hidden1w8 -0.811765
#define hidden1b -0.741176
#define hidden2w0 -0.772549
#define hidden2w1 0.639216
#define hidden2w2 0.105882
#define hidden2w3 0.443137
#define hidden2w4 0.905882
#define hidden2w5 -0.898039
#define hidden2w6 -0.780392
#define hidden2w7 -0.984314
#define hidden2w8 -0.270588
#define hidden2b -0.341176
#define hidden3w0 0.309804
#define hidden3w1 0.717647
#define hidden3w2 1.000000
#define hidden3w3 0.662745
#define hidden3w4 -0.490196
#define hidden3w5 0.364706
#define hidden3w6 -0.254902
#define hidden3w7 0.474510
#define hidden3w8 -0.600000
#define hidden3b -0.474510
#define hidden4w0 -0.568627
#define hidden4w1 -0.623529
#define hidden4w2 -0.796078
#define hidden4w3 -0.145098
#define hidden4w4 -0.356863
#define hidden4w5 -0.898039
#define hidden4w6 0.584314
#define hidden4w7 -0.129412
#define hidden4w8 0.576471
#define hidden4b -0.380392
#define hidden5w0 0.811765
#define hidden5w1 -0.952941
#define hidden5w2 -0.968627
#define hidden5w3 -0.333333
#define hidden5w4 -0.796078
#define hidden5w5 0.294118
#define hidden5w6 0.968627
#define hidden5w7 0.505882
#define hidden5w8 -0.709804
#define hidden5b 0.215686
#define hidden6w0 1.000000
#define hidden6w1 0.372549
#define hidden6w2 -0.215686
#define hidden6w3 -0.427451
#define hidden6w4 0.819608
#define hidden6w5 -0.701961
#define hidden6w6 -0.945098
#define hidden6w7 -0.003922
#define hidden6w8 -0.309804
#define hidden6b -0.521569
#define hidden7w0 -0.592157
#define hidden7w1 0.976471
#define hidden7w2 0.200000
#define hidden7w3 -0.866667
#define hidden7w4 -0.709804
#define hidden7w5 -0.050980
#define hidden7w6 -0.443137
#define hidden7w7 0.615686
#define hidden7w8 0.592157
#define hidden7b -0.898039
#define hidden8w0 -0.309804
#define hidden8w1 -0.019608
#define hidden8w2 -0.968627
#define hidden8w3 0.639216
#define hidden8w4 0.686275
#define hidden8w5 0.113726
#define hidden8w6 -0.552941
#define hidden8w7 -0.184314
#define hidden8w8 -0.050980
#define hidden8b -0.498039
#define outputw0 -0.333333
#define outputw1 0.168628
#define outputw2 0.584314
#define outputw3 0.184314
#define outputw4 -0.145098
#define outputw5 0.450980
#define outputw6 0.388235
#define outputw7 -0.341176
#define outputw8 0.223529
#define outputb 0.027451

#endif
