/*
 * Buffer scoring AI, autogenerated scores
 *
 * Copyright (C) 2014 Lauri Kasanen   All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef MAGIC_H
#define MAGIC_H

#define input0w 0.290490
#define input0b 0.327330
#define input1w 0.322020
#define input1b 0.117550
#define input2w 0.238620
#define input2b 0.175600
#define input3w 0.084350
#define input3b 0.396200
#define input4w 0.245370
#define input4b 0.175260
#define input5w 0.137360
#define input5b 0.303800
#define input6w 0.165370
#define input6b 0.237300
#define input7w 0.887000
#define input7b 0.560900
#define input8w 0.203900
#define input8b 0.475300
#define hidden0w0 0.409700
#define hidden0w1 0.146310
#define hidden0w2 0.113830
#define hidden0w3 0.264830
#define hidden0w4 0.118760
#define hidden0w5 0.191500
#define hidden0w6 0.202520
#define hidden0w7 0.249880
#define hidden0w8 0.311440
#define hidden0b 0.157150
#define hidden1w0 0.173160
#define hidden1w1 0.219520
#define hidden1w2 0.197950
#define hidden1w3 0.812000
#define hidden1w4 0.247120
#define hidden1w5 0.156960
#define hidden1w6 0.112100
#define hidden1w7 0.110970
#define hidden1w8 0.211700
#define hidden1b 0.960700
#define hidden2w0 0.118860
#define hidden2w1 0.971300
#define hidden2w2 0.289240
#define hidden2w3 0.819000
#define hidden2w4 0.234100
#define hidden2w5 0.231660
#define hidden2w6 0.193090
#define hidden2w7 0.305320
#define hidden2w8 0.321260
#define hidden2b 0.321190
#define hidden3w0 0.292340
#define hidden3w1 0.205020
#define hidden3w2 0.227890
#define hidden3w3 0.205940
#define hidden3w4 0.123820
#define hidden3w5 0.213740
#define hidden3w6 0.233990
#define hidden3w7 0.145980
#define hidden3w8 0.139210
#define hidden3b 0.757400
#define hidden4w0 0.813400
#define hidden4w1 0.231690
#define hidden4w2 0.287460
#define hidden4w3 0.826400
#define hidden4w4 0.260240
#define hidden4w5 0.775900
#define hidden4w6 0.956000
#define hidden4w7 0.399700
#define hidden4w8 0.218410
#define hidden4b 0.223090
#define hidden5w0 0.127220
#define hidden5w1 0.181150
#define hidden5w2 0.117420
#define hidden5w3 0.223760
#define hidden5w4 0.613000
#define hidden5w5 0.291520
#define hidden5w6 0.146250
#define hidden5w7 0.121610
#define hidden5w8 0.366600
#define hidden5b 0.220100
#define hidden6w0 0.851200
#define hidden6w1 0.261010
#define hidden6w2 0.708600
#define hidden6w3 0.259530
#define hidden6w4 0.103600
#define hidden6w5 0.229000
#define hidden6w6 0.110360
#define hidden6w7 0.141000
#define hidden6w8 0.246100
#define hidden6b 0.853100
#define hidden7w0 0.155800
#define hidden7w1 0.158520
#define hidden7w2 0.142760
#define hidden7w3 0.302870
#define hidden7w4 0.136610
#define hidden7w5 0.288640
#define hidden7w6 0.139700
#define hidden7w7 0.275000
#define hidden7w8 0.287490
#define hidden7b 0.399600
#define hidden8w0 0.241500
#define hidden8w1 0.209670
#define hidden8w2 0.109890
#define hidden8w3 0.303720
#define hidden8w4 0.241310
#define hidden8w5 0.288160
#define hidden8w6 0.227710
#define hidden8w7 0.277330
#define hidden8w8 0.147650
#define hidden8b 0.098560
#define outputw0 0.064020
#define outputw1 0.021001
#define outputw2 0.044050
#define outputw3 0.031930
#define outputw4 0.022434
#define outputw5 0.020810
#define outputw6 0.075358
#define outputw7 0.066667
#define outputw8 0.097310
#define outputb 0.004567

#endif
