/*
 * Buffer scoring AI, autogenerated scores
 *
 * Copyright (C) 2014 Lauri Kasanen   All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef MAGIC_H
#define MAGIC_H

#define input0w -0.314706
#define input0b -0.790196
#define input1w 0.257753
#define input1b -0.019608
#define input2w 0.540092
#define input2b -0.885294
#define input3w 0.197647
#define input3b -1.029412
#define input4w 0.204510
#define input4b -0.291176
#define input5w -0.378431
#define input5b -0.426078
#define input6w 2.628755
#define input6b 0.388235
#define input7w 0.552941
#define input7b -0.795098
#define input8w 0.342745
#define input8b 0.835294
#define hidden0w0 -0.294118
#define hidden0w1 -0.835294
#define hidden0w2 0.383333
#define hidden0w3 -0.069608
#define hidden0w4 -0.388235
#define hidden0w5 0.741176
#define hidden0w6 -0.563726
#define hidden0w7 -0.808824
#define hidden0w8 0.137255
#define hidden0b -0.162745
#define hidden1w0 -0.778431
#define hidden1w1 -0.626471
#define hidden1w2 0.471521
#define hidden1w3 -0.145098
#define hidden1w4 -0.416667
#define hidden1w5 0.772549
#define hidden1w6 -0.301961
#define hidden1w7 -0.471569
#define hidden1w8 0.945098
#define hidden1b -0.992157
#define hidden2w0 -0.450980
#define hidden2w1 0.011765
#define hidden2w2 -0.874510
#define hidden2w3 1.000000
#define hidden2w4 -0.234902
#define hidden2w5 -1.030000
#define hidden2w6 0.584314
#define hidden2w7 -0.129412
#define hidden2w8 -0.607843
#define hidden2b 0.932941
#define hidden3w0 -0.351961
#define hidden3w1 0.035294
#define hidden3w2 -0.122549
#define hidden3w3 0.913725
#define hidden3w4 -0.992157
#define hidden3w5 0.455882
#define hidden3w6 0.799020
#define hidden3w7 -0.631373
#define hidden3w8 0.647059
#define hidden3b -0.960784
#define hidden4w0 -0.500980
#define hidden4w1 0.968627
#define hidden4w2 0.591831
#define hidden4w3 0.030392
#define hidden4w4 0.698029
#define hidden4w5 -0.887255
#define hidden4w6 -0.304902
#define hidden4w7 -0.673529
#define hidden4w8 0.592157
#define hidden4b -0.367647
#define hidden5w0 -0.565686
#define hidden5w1 0.462632
#define hidden5w2 0.090196
#define hidden5w3 -0.390196
#define hidden5w4 -0.145098
#define hidden5w5 -0.204902
#define hidden5w6 -0.490196
#define hidden5w7 -0.772549
#define hidden5w8 0.665686
#define hidden5b -0.160784
#define hidden6w0 0.215686
#define hidden6w1 -0.215686
#define hidden6w2 0.798529
#define hidden6w3 0.968807
#define hidden6w4 -0.396078
#define hidden6w5 0.890196
#define hidden6w6 0.411765
#define hidden6w7 0.247059
#define hidden6w8 0.807408
#define hidden6b 0.048039
#define hidden7w0 0.239216
#define hidden7w1 0.033333
#define hidden7w2 0.325490
#define hidden7w3 -0.162745
#define hidden7w4 0.913725
#define hidden7w5 0.003922
#define hidden7w6 -0.976471
#define hidden7w7 -0.199020
#define hidden7w8 0.380392
#define hidden7b 0.377299
#define hidden8w0 0.391177
#define hidden8w1 0.764706
#define hidden8w2 -0.615686
#define hidden8w3 0.686275
#define hidden8w4 -0.427451
#define hidden8w5 -0.498039
#define hidden8w6 0.780392
#define hidden8w7 0.043137
#define hidden8w8 0.145098
#define hidden8b 0.338235
#define outputw0 -0.164706
#define outputw1 -0.983725
#define outputw2 0.422549
#define outputw3 0.796651
#define outputw4 -0.918235
#define outputw5 0.973769
#define outputw6 0.479217
#define outputw7 0.499020
#define outputw8 -0.965294
#define outputb 0.297348

#endif
