/*
 * Buffer scoring AI, autogenerated scores
 *
 * Copyright (C) 2014 Lauri Kasanen   All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef MAGIC_H
#define MAGIC_H

#define input0w 0.976471
#define input0b -0.788235
#define input1w 0.247059
#define input1b 0.152941
#define input2w -2.623529
#define input2b -0.882353
#define input3w 1.823530
#define input3b 2.788235
#define input4w -0.882353
#define input4b -2.788235
#define input5w -0.435294
#define input5b -0.435294
#define input6w 2.976470
#define input6b 0.388235
#define input7w -2.411765
#define input7b -2.458823
#define input8w 0.670588
#define input8b 0.835294
#define hidden0w0 -0.294118
#define hidden0w1 -2.858824
#define hidden0w2 0.388235
#define hidden0w3 -0.058824
#define hidden0w4 -0.388235
#define hidden0w5 -0.905882
#define hidden0w6 -1.752941
#define hidden0w7 1.423530
#define hidden0w8 -1.752941
#define hidden0b -2.388235
#define hidden1w0 1.682353
#define hidden1w1 -0.623529
#define hidden1w2 0.482353
#define hidden1w3 -0.152941
#define hidden1w4 -0.411765
#define hidden1w5 -0.317647
#define hidden1w6 1.282353
#define hidden1w7 -2.364706
#define hidden1w8 -1.423529
#define hidden1b 0.882353
#define hidden2w0 1.258823
#define hidden2w1 -1.117647
#define hidden2w2 -0.882353
#define hidden2w3 -2.647059
#define hidden2w4 -0.223529
#define hidden2w5 2.670588
#define hidden2w6 0.905882
#define hidden2w7 -0.129412
#define hidden2w8 -0.600000
#define hidden2b 0.176471
#define hidden3w0 -0.341177
#define hidden3w1 0.247059
#define hidden3w2 -0.129412
#define hidden3w3 0.905882
#define hidden3w4 -1.000000
#define hidden3w5 0.458824
#define hidden3w6 1.211765
#define hidden3w7 -2.200000
#define hidden3w8 0.647059
#define hidden3b -0.858824
#define hidden4w0 -0.505882
#define hidden4w1 0.976471
#define hidden4w2 0.600000
#define hidden4w3 -1.094118
#define hidden4w4 1.305882
#define hidden4w5 -0.011765
#define hidden4w6 -2.317647
#define hidden4w7 0.058824
#define hidden4w8 1.611765
#define hidden4b 0.247059
#define hidden5w0 0.788235
#define hidden5w1 0.458824
#define hidden5w2 -1.329412
#define hidden5w3 0.223530
#define hidden5w4 2.411765
#define hidden5w5 0.411765
#define hidden5w6 -2.317647
#define hidden5w7 0.294118
#define hidden5w8 0.341177
#define hidden5b 0.247059
#define hidden6w0 -2.600000
#define hidden6w1 -0.223529
#define hidden6w2 0.788235
#define hidden6w3 1.541177
#define hidden6w4 0.835294
#define hidden6w5 -1.658823
#define hidden6w6 -0.623529
#define hidden6w7 -1.400000
#define hidden6w8 -2.552941
#define hidden6b -2.364706
#define hidden7w0 0.247059
#define hidden7w1 0.600000
#define hidden7w2 0.317647
#define hidden7w3 -0.152941
#define hidden7w4 0.905882
#define hidden7w5 0.223530
#define hidden7w6 -1.188235
#define hidden7w7 -0.200000
#define hidden7w8 0.388235
#define hidden7b 0.388235
#define hidden8w0 0.623529
#define hidden8w1 0.764706
#define hidden8w2 1.188235
#define hidden8w3 1.729412
#define hidden8w4 -0.435294
#define hidden8w5 2.929412
#define hidden8w6 0.788235
#define hidden8w7 -1.776471
#define hidden8w8 -0.011765
#define hidden8b 0.341177
#define outputw0 0.717647
#define outputw1 2.647059
#define outputw2 0.411765
#define outputw3 2.482353
#define outputw4 0.223530
#define outputw5 0.976471
#define outputw6 0.811765
#define outputw7 1.611765
#define outputw8 -1.870588
#define outputb -0.011765

#endif
